# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'RxMoyaDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for RxMoyaDemo
  pod 'Moya/RxSwift'
  pod 'Moya/ReactiveCocoa'
  pod 'Moya-ObjectMapper/RxSwift'
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxBlocking'
  pod 'RxDataSources'
  
  pod 'SwiftyJSON'
  pod 'RealmSwift'
  pod 'HanekeSwift'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'
  
  # Loading spinner / activity indicator
  pod "JHSpinner"
  
end
